version = "0.2"

# ---------------------------------------------------------
#  COMMIT TYPES
# ---------------------------------------------------------
[types]
INIT = "Initial commit / project bootstrap"
WIP = "Work in progress — not ready to merge"
FEAT = "New feature"
FIX = "Bug fix"
CHORE = "Maintenance / tooling / dependencies"
DOCS = "Documentation only"
REFACTOR = "Refactor without behavior change"
STYLE = "Formatting, lint fixes"
TEST = "Add or update tests"
PERF = "Performance improvement"
BUILD = "Build / packaging / release"
# ---------------------------------------------------------
#  COMMIT SCOPES
# ---------------------------------------------------------
[scopes]
accept = "list"

list = [
 "cli",
  "generator",
  "template",
  "project-structure",
  "config",
  "dependencies",
  "typing",
  "lint",
  "docs",
  "release"
]
# ---------------------------------------------------------
#  TICKET CONFIG
# ---------------------------------------------------------
[ticket]
required = false
prefixes = ["#"]


[templates]
commit = """
{{ type }} {{ description }}{% if scope %} ({{ scope }}){% endif %}{% if ticket %} — {% if type == "WIP" %}Refs{% else %}Closes{% endif %} {{ ticket }}{% endif %}

# Optional detailed description below:

"""